name: Build and Push Docker Image

on:
  # Manually trigger the workflow via the GitHub UI
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #  tags:
  #    - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get latest upstream version
        id: upstream_version
        run: |
          VERSION=$(curl -s "https://api.github.com/repos/mingrammer/diagrams/releases/latest" | jq -r .tag_name)
          echo "UPSTREAM_VERSION=${VERSION#v}" >> $GITHUB_ENV  # Removes the "v" prefix

      - name: Get my version
        id: my_version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "MY_VERSION=${VERSION#v}" >> $GITHUB_ENV  # Removes the "v" prefix            

      - name: Log in to Docker Hub
        if: ${{ env.UPSTREAM_VERSION != '' && env.MY_VERSION != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: ${{ env.UPSTREAM_VERSION != '' && env.MY_VERSION != '' }}
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: ${{ env.UPSTREAM_VERSION != '' && env.MY_VERSION != '' }}
        uses: docker/build-push-action@v5
        with:
          context: ./docker_build
          push: true
          tags: |
            kianda/diagrams-wrapper:latest
            kianda/diagrams-wrapper:v${{ env.UPSTREAM_VERSION }}-v${{ env.MY_VERSION }}
